# Generated by Django 4.2.7 on 2025-10-10 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrollmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_started", "Session démarrée"),
                            ("payload_received", "Payload reçu"),
                            ("validation_started", "Validation démarrée"),
                            ("validation_completed", "Validation terminée"),
                            ("abis_check_started", "Vérification ABIS démarrée"),
                            ("abis_check_completed", "Vérification ABIS terminée"),
                            ("fgp_core_created", "FGP Core créé"),
                            ("extensions_created", "Extensions créées"),
                            ("session_completed", "Session terminée"),
                            ("session_failed", "Session échouée"),
                        ],
                        help_text="Type d'événement",
                        max_length=30,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, help_text="Données de l'événement"),
                ),
                ("message", models.TextField(help_text="Message descriptif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Événement d'enrôlement",
                "verbose_name_plural": "Événements d'enrôlement",
                "db_table": "enrollment_events",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nin", models.CharField(help_text="NIN généré", max_length=20)),
                (
                    "receipt_number",
                    models.CharField(
                        help_text="Numéro de récépissé", max_length=50, unique=True
                    ),
                ),
                ("receipt_content", models.JSONField(help_text="Contenu du récépissé")),
                (
                    "receipt_pdf_url",
                    models.URLField(blank=True, help_text="URL du PDF", null=True),
                ),
                ("qr_code_data", models.TextField(help_text="Données du QR code")),
                (
                    "qr_code_url",
                    models.URLField(blank=True, help_text="URL du QR code", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Date d'expiration")),
            ],
            options={
                "verbose_name": "Récépissé d'enrôlement",
                "verbose_name_plural": "Récépissés d'enrôlement",
                "db_table": "enrollment_receipts",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="ID de session unique", max_length=100, unique=True
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("fixed", "Poste fixe"),
                            ("mobile", "Mobile"),
                            ("itinerant", "Itinérant"),
                            ("school", "École"),
                            ("pnc", "PNC"),
                            ("fardc", "FARDC"),
                            ("prison", "Prison"),
                            ("refugee", "Réfugiés"),
                            ("ceni", "CENI"),
                        ],
                        help_text="Canal d'enrôlement",
                        max_length=20,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(help_text="ID du dispositif", max_length=100),
                ),
                (
                    "operator_id",
                    models.CharField(help_text="ID de l'opérateur", max_length=100),
                ),
                (
                    "location",
                    models.JSONField(
                        help_text="Localisation (province, territoire, etc.)"
                    ),
                ),
                ("payload", models.JSONField(help_text="Payload complet d'enrôlement")),
                (
                    "payload_hash",
                    models.CharField(help_text="Hash du payload", max_length=64),
                ),
                (
                    "payload_signature",
                    models.TextField(blank=True, help_text="Signature JWS", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("VALIDATING", "En validation"),
                            ("PROCESSING", "En traitement"),
                            ("ABIS_CHECK", "Vérification ABIS"),
                            ("REVIEW", "En révision"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        help_text="Statut de la session",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Pourcentage de progression"
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True, help_text="NIN généré", max_length=20, null=True
                    ),
                ),
                (
                    "fgp_core_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "extensions_status",
                    models.JSONField(
                        default=dict, help_text="Statut des extensions par strate"
                    ),
                ),
                (
                    "abis_result",
                    models.JSONField(default=dict, help_text="Résultat ABIS"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Message d'erreur", null=True
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(default=list, help_text="Erreurs de validation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Temps de traitement en ms", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Session d'enrôlement",
                "verbose_name_plural": "Sessions d'enrôlement",
                "db_table": "enrollment_sessions",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("schema", "Validation du schéma"),
                            ("business", "Validation métier"),
                            ("biometric", "Validation biométrique"),
                            ("document", "Validation des documents"),
                            ("duplicate", "Vérification des doublons"),
                        ],
                        help_text="Type de validation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PASSED", "Validé"),
                            ("FAILED", "Échoué"),
                            ("WARNING", "Avertissement"),
                        ],
                        default="PENDING",
                        help_text="Statut de validation",
                        max_length=20,
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(help_text="Règles de validation appliquées"),
                ),
                (
                    "validation_result",
                    models.JSONField(help_text="Résultat de validation"),
                ),
                (
                    "error_details",
                    models.JSONField(default=list, help_text="Détails des erreurs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session d'enrôlement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="enrollment.enrollmentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation d'enrôlement",
                "verbose_name_plural": "Validations d'enrôlement",
                "db_table": "enrollment_validations",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentStatistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Date des statistiques")),
                (
                    "channel",
                    models.CharField(help_text="Canal d'enrôlement", max_length=20),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("completed_sessions", models.IntegerField(default=0)),
                ("failed_sessions", models.IntegerField(default=0)),
                ("abis_hits", models.IntegerField(default=0)),
                ("abis_reviews", models.IntegerField(default=0)),
                ("avg_processing_time_ms", models.IntegerField(default=0)),
                ("min_processing_time_ms", models.IntegerField(default=0)),
                ("max_processing_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Statistique d'enrôlement",
                "verbose_name_plural": "Statistiques d'enrôlement",
                "db_table": "enrollment_statistics",
                "unique_together": {("date", "channel")},
            },
        ),
        migrations.AddIndex(
            model_name="enrollmentsession",
            index=models.Index(
                fields=["session_id"], name="enrollment__session_c6ad7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentsession",
            index=models.Index(fields=["status"], name="enrollment__status_f11fc0_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollmentsession",
            index=models.Index(
                fields=["channel"], name="enrollment__channel_91c4af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentsession",
            index=models.Index(
                fields=["created_at"], name="enrollment__created_c28e39_idx"
            ),
        ),
        migrations.AddField(
            model_name="enrollmentreceipt",
            name="session",
            field=models.OneToOneField(
                help_text="Session d'enrôlement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="enrollment.enrollmentsession",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="session",
            field=models.ForeignKey(
                help_text="Session d'enrôlement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="enrollment.enrollmentsession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentvalidation",
            unique_together={("session", "validation_type")},
        ),
        migrations.AddIndex(
            model_name="enrollmentevent",
            index=models.Index(
                fields=["session", "event_type"], name="enrollment__session_f8de19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentevent",
            index=models.Index(
                fields=["created_at"], name="enrollment__created_13330e_idx"
            ),
        ),
    ]
