# Generated by Django 4.2.7 on 2024-01-07 20:01

import core.models.fields.date_field
import core.models.fields.json_field
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('destination', models.CharField(max_length=255, null=True, verbose_name='destination')),
                ('start_date', core.models.fields.date_field.DateField(null=True, verbose_name='date de début')),
                ('end_date', core.models.fields.date_field.DateField(null=True, verbose_name='date de fin')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('employees', core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(to='employee.employee', verbose_name='employés')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('document', models.FileField(default=None, null=True, upload_to=core.utils.upload_directory_file, verbose_name='document')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('employee', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='employé')),
                ('mission', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.mission', verbose_name='mission')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'ordering': ('-id',),
            },
        ),
    ]
