# Generated by Django 4.2.7 on 2024-01-08 13:05

import core.models.managers.user
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.managers.user.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="importer",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "en cours"),
                    ("pending", "en attente"),
                    ("success", "succès"),
                    ("error", "erreur"),
                ],
                default="pending",
                max_length=255,
                verbose_name="message",
            ),
        ),
    ]
