# Generated by Django 4.2.7 on 2024-01-08 13:05

import core.models.fields.model_select_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("masculin", "masculin"), ("féminin", "féminin")],
                max_length=10,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[("marié", "marié"), ("célibataire", "célibataire")],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "cash"),
                    ("banque", "banque"),
                    ("mobile money", "mobile money"),
                ],
                max_length=20,
                verbose_name="mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub_direction",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.subdirection",
                verbose_name="sous-direction",
            ),
        ),
    ]
