# Generated by Django 4.2.7 on 2024-01-08 14:30

import core.models.fields.date_field
import core.utils
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee",
            "0002_alter_employee_gender_alter_employee_marital_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="appointment_letter",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="employee/appointment_letter",
                verbose_name="lettre de nomination",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="appointment_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="numéro de nomination",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="citizenship",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="nationalité",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_expiry",
            field=core.models.fields.date_field.DateField(
                default=None, null=True, verbose_name="date d'expiration"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_issue",
            field=core.models.fields.date_field.DateField(
                default=None, null=True, verbose_name="date de délivrance"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="email_professional",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email professional",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="contact d'urgence",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region=None,
                verbose_name="numéro de téléphone d'urgence",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="home_country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="pays d'origine",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="home_province",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="province d'origine",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="home_sector",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="secteur d'origine",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="home_territory",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="territoire d'origine",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="home_village",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="village d'origine",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="identity_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="numéro de pièce d'identité",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="place_of_birth",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="lieu de naissance",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="place_of_issue",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="lieu de délivrance",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="refering_doctor",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="médecin référent",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="refering_doctor_email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email du médecin référent",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="refering_doctor_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region=None,
                verbose_name="numéro de téléphone du médecin référent",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="relationship",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="relation",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="telephone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region=None,
                verbose_name="numéro de téléphone professional",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="type_of_identity",
            field=models.CharField(
                choices=[
                    ("national_id", "national id"),
                    ("passport", "passport"),
                    ("driver_license", "permis de conduire"),
                    ("document", "document"),
                    ("other", "other"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="type de pièce d'identité",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="birth_certificate",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="certificat de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_of_birth",
            field=core.models.fields.date_field.DateField(
                blank=True, default=None, null=True, verbose_name="date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                default=None, max_length=100, null=True, verbose_name="diplôme"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=core.models.fields.date_field.DateField(
                blank=True, default=None, null=True, verbose_name="date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=core.models.fields.date_field.DateField(
                blank=True, default=None, null=True, verbose_name="date de début"
            ),
        ),
    ]
