# Generated by Django 4.2.7 on 2024-01-14 09:50

import core.models.fields.model_select_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_employee_appointment_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="agreement",
            field=core.models.fields.model_select_field.ModelSelect(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.agreement",
                verbose_name="type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "masculin"), ("female", "féminin")],
                max_length=10,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[("maried", "marié(e)"), ("single", "célibataire")],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "cash"),
                    ("bank", "banque"),
                    ("mobile money", "mobile money"),
                ],
                max_length=20,
                verbose_name="mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="type_of_identity",
            field=models.CharField(
                choices=[
                    ("driver_license", "permis de conduire"),
                    ("voter's card", "carte d'électeur"),
                    ("national_id", "national id"),
                    ("passport", "passeport"),
                    ("document", "document"),
                    ("other", "other"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="type de pièce d'identité",
            ),
        ),
    ]
