# Generated by Django 4.2.7 on 2026-06-20 16:37

import core.models.fields.json_field
import core.models.fields.model_select_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_alter_employee_agreement_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code période')),
                ('label', models.CharField(max_length=100, verbose_name='libellé')),
                ('bank', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='banque')),
                ('institution', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='institution')),
                ('effectifs', models.PositiveIntegerField(default=0, verbose_name='effectifs')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'période de paie',
                'verbose_name_plural': 'périodes de paie',
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('line_number', models.PositiveIntegerField(default=0, verbose_name='n° ligne')),
                ('registration_number', models.CharField(db_index=True, max_length=50, verbose_name='matricule / NIU')),
                ('full_name', models.CharField(max_length=255, verbose_name='nom complet')),
                ('fonction', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='fonction')),
                ('base', models.BigIntegerField(default=0, verbose_name='base')),
                ('prime', models.BigIntegerField(default=0, verbose_name='prime')),
                ('logement', models.BigIntegerField(default=0, verbose_name='logement')),
                ('ipr', models.BigIntegerField(default=0, verbose_name='IPR')),
                ('cpa', models.BigIntegerField(default=0, verbose_name='CPA')),
                ('montant_net', models.BigIntegerField(default=0, verbose_name='montant net')),
                ('ftc', models.BigIntegerField(default=0, verbose_name='FTC')),
                ('net_a_payer', models.BigIntegerField(default=0, verbose_name='net à payer')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('employee', core.models.fields.model_select_field.ModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_lines', to='employee.employee', verbose_name='employé')),
                ('period', core.models.fields.model_select_field.ModelSelect(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='employee.payrollperiod', verbose_name='période')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'ligne de paie',
                'verbose_name_plural': 'lignes de paie',
            },
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('period', 'registration_number'), name='uniq_payroll_line_period_matricule'),
        ),
    ]
