# Generated by Django 4.2.7 on 2026-06-24 04:48

import core.models.fields.cascade_model_select_field
import core.models.fields.date_field
import core.models.fields.json_field
import core.models.fields.model_select_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


def load_geography_from_dossier_only(apps, schema_editor):
    from employee.utils.geography import load_geography_from_dossier

    load_geography_from_dossier()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_latejustification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FgpFingerprintCapture',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50)),
                ('finger_position', models.CharField(max_length=20)),
                ('capture_status', models.CharField(max_length=20)),
                ('template_uri', models.URLField(blank=True, null=True)),
                ('template_format', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'fgp_fingerprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'secteur',
                'verbose_name_plural': 'secteurs',
                'ordering': ('territory__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('province', core.models.fields.model_select_field.ModelSelect(on_delete=django.db.models.deletion.CASCADE, to='employee.province', verbose_name='province')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'territoire',
                'verbose_name_plural': 'territoires',
                'ordering': ('province__name', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'pointage', 'verbose_name_plural': 'pointages'},
        ),
        migrations.AddField(
            model_name='education',
            name='diploma_year',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="année d'obtention du diplôme"),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='domaine'),
        ),
        migrations.AddField(
            model_name='education',
            name='study_level',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="niveau d'étude"),
        ),
        migrations.AddField(
            model_name='employee',
            name='onip_start_date',
            field=core.models.fields.date_field.DateField(blank=True, default=None, null=True, verbose_name='date début de travail ONIP'),
        ),
        migrations.AlterField(
            model_name='latejustification',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AlterField(
            model_name='latejustification',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('sector', core.models.fields.model_select_field.ModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.sector', verbose_name='secteur')),
                ('territory', core.models.fields.model_select_field.ModelSelect(on_delete=django.db.models.deletion.CASCADE, to='employee.territory', verbose_name='territoire')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'village',
                'verbose_name_plural': 'villages',
                'ordering': ('territory__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='territory',
            field=core.models.fields.model_select_field.ModelSelect(on_delete=django.db.models.deletion.CASCADE, to='employee.territory', verbose_name='territoire'),
        ),
        migrations.AddField(
            model_name='sector',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par'),
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='home_province',
            new_name='home_province_text',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='home_territory',
            new_name='home_territory_text',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='home_sector',
            new_name='home_sector_text',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='home_village',
            new_name='home_village_text',
        ),
        migrations.AddField(
            model_name='employee',
            name='home_province',
            field=core.models.fields.model_select_field.ModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.province', verbose_name="province d'origine"),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_territory',
            field=core.models.fields.cascade_model_select_field.CascadeModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.territory', verbose_name="territoire d'origine"),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_sector',
            field=core.models.fields.cascade_model_select_field.CascadeModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.sector', verbose_name="secteur d'origine"),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_village',
            field=core.models.fields.cascade_model_select_field.CascadeModelSelect(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.village', verbose_name="village d'origine"),
        ),
        migrations.RunPython(load_geography_from_dossier_only, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employee',
            name='home_province_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='home_territory_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='home_sector_text',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='home_village_text',
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('territory', 'sector', 'name'), name='uniq_village_per_territory_sector'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='uniq_territory_per_province'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('territory', 'name'), name='uniq_sector_per_territory'),
        ),
    ]
