#ifndef MPH_RT_SVNREVISION_H_INCLUDED
#define MPH_RT_SVNREVISION_H_INCLUDED
#define RT_SVN_REVISION 783
#define RT_SVN_REVISION_STR "783"
#define RT_SVN_REVISION_YEAR 2017
#define RT_SVN_REVISION_YEAR_STR "2017"
#define RT_SVN_REVISION_MONTH 1
#define RT_SVN_REVISION_MONTH_STR "1"
#define RT_SVN_UP_TO_DATE
#if RT_SVN_REVISION == 0
#error BAD_SVN_REVISION
#endif
#endif // !defined(MPH_RT_SVNREVISION_H_INCLUDED)
