"""Catalogues de référence — formations et établissements ONIP."""

AUTRES_CODE = 'AUTRES'
AUTRE_CODE = 'AUTRE'

STUDY_LEVELS = (
    ('AUCUN', 'Aucun', 1),
    ('PRIMAIRE', 'Primaire', 2),
    ('SECONDAIRE', 'Secondaire', 3),
    ('HUMANITES', 'Humanités', 4),
    ('GRADUAT_BAC3', 'Graduat (Bac+3)', 5),
    ('LICENCE_BAC5', 'Licence (Bac+5)', 6),
    ('MASTER', 'Master', 7),
    ('DEA', 'DEA', 8),
    ('DOCTORAT_PHD', 'Doctorat (PhD)', 9),
    ('POST_DOCTORAT', 'Post-doctorat', 10),
    ('FORMATION_PROFESSIONNELLE', 'Formation professionnelle', 11),
    ('CERTIFICAT_SPECIALISE', 'Certificat spécialisé', 12),
    (AUTRES_CODE, 'Autres', 99),
)

DEGREES = (
    ('CERTIFICAT_ETUDES_PRIMAIRES', "Certificat d'études primaires", 1),
    ('DIPLOME_ETAT', "Diplôme d'État", 2),
    ('GRADUAT', 'Graduat', 3),
    ('LICENCE', 'Licence', 4),
    ('MASTER', 'Master', 5),
    ('DEA', 'DEA', 6),
    ('DOCTORAT', 'Doctorat', 7),
    ('BTS', 'BTS', 8),
    ('INGENIEUR', 'Ingénieur', 9),
    ('MEDECIN', 'Médecin', 10),
    ('PHARMACIEN', 'Pharmacien', 11),
    ('ARCHITECTE', 'Architecte', 12),
    (AUTRE_CODE, 'Autre', 99),
)

FIELDS_OF_STUDY = (
    ('MATHEMATIQUE_INFORMATIQUE', 'Mathématique-Informatique', 10),
    ('GENIE_LOGICIEL', 'Génie logiciel', 11),
    ('RESEAUX', 'Réseaux', 12),
    ('TELECOMMUNICATIONS', 'Télécommunications', 13),
    ('INTELLIGENCE_ARTIFICIELLE', 'Intelligence artificielle', 14),
    ('CYBERSECURITE', 'Cybersécurité', 15),
    ('INFORMATIQUE', 'Informatique', 16),
    ('MATHEMATIQUES', 'Mathématiques', 20),
    ('STATISTIQUES', 'Statistiques', 21),
    ('DEMOGRAPHIE', 'Démographie', 22),
    ('ECONOMIE', 'Économie', 30),
    ('GESTION', 'Gestion', 31),
    ('COMPTABILITE', 'Comptabilité', 32),
    ('DROIT', 'Droit', 40),
    ('SCIENCES_POLITIQUES', 'Sciences politiques', 41),
    ('RELATIONS_INTERNATIONALES', 'Relations internationales', 42),
    ('ADMINISTRATION_PUBLIQUE', 'Administration publique', 43),
    ('ADMINISTRATION', 'Administration', 44),
    ('FINANCE', 'Finance', 50),
    ('BANQUE', 'Banque', 51),
    ('MARKETING', 'Marketing', 52),
    ('RESSOURCES_HUMAINES', 'Ressources humaines', 53),
    ('COMMUNICATION', 'Communication', 60),
    ('JOURNALISME', 'Journalisme', 61),
    ('MEDECINE', 'Médecine', 70),
    ('SANTE_PUBLIQUE', 'Santé publique', 71),
    ('AGRONOMIE', 'Agronomie', 80),
    ('GENIE_CIVIL', 'Génie civil', 81),
    ('ARCHITECTURE', 'Architecture', 82),
    ('ELECTRICITE', 'Électricité', 83),
    ('MECANIQUE', 'Mécanique', 84),
    ('CHIMIE', 'Chimie', 90),
    ('PHYSIQUE', 'Physique', 91),
    ('BIOLOGIE', 'Biologie', 92),
    ('GEOGRAPHIE', 'Géographie', 100),
    ('HISTOIRE', 'Histoire', 101),
    ('PSYCHOLOGIE', 'Psychologie', 102),
    ('SOCIOLOGIE', 'Sociologie', 103),
    ('PHILOSOPHIE', 'Philosophie', 104),
    ('LANGUES', 'Langues', 105),
    ('ENSEIGNEMENT', 'Enseignement', 106),
    ('GEOSCIENCES', 'Géosciences', 107),
    ('ORIENTATION_SCOLAIRE_PEDAGOGIQUE', 'Orientation scolaire et pédagogique', 108),
    (AUTRES_CODE, 'Autres', 999),
)

INSTITUTIONS_PUBLIC = (
    ('UNIKIN', 'Université de Kinshasa', 10),
    ('UPN', 'Université Pédagogique Nationale', 11),
    ('UNILU', 'Université de Lubumbashi', 12),
    ('UNIKIS', 'Université de Kisangani', 13),
    ('UNIMBA', 'Université de Mbandaka', 14),
    ('UNIGOM', 'Université de Goma', 15),
    ('UNIKOL', 'Université de Kolwezi', 16),
    ('UNIKINDU', 'Université de Kindu', 17),
)

INSTITUTIONS_PRIVATE = (
    ('UPC', 'Université Protestante au Congo', 110),
    ('UCC', 'Université Catholique du Congo', 111),
    ('ULK', 'Université Libre de Kinshasa', 112),
    ('USK', 'Université Simon Kimbangu', 113),
    ('UWB', 'Université William Booth', 114),
    ('URK', 'Université Révérend Kim', 115),
)

INSTITUTIONS_OTHER = (
    (AUTRES_CODE, 'Autres', 999),
)

STUDY_LEVEL_ALIASES = {
    'aucun': 'AUCUN',
    'none': 'AUCUN',
    'primaire': 'PRIMAIRE',
    'secondaire': 'SECONDAIRE',
    'humanites': 'HUMANITES',
    'humanite': 'HUMANITES',
    'graduat': 'GRADUAT_BAC3',
    'graduat bac3': 'GRADUAT_BAC3',
    'licence': 'LICENCE_BAC5',
    'licence bac5': 'LICENCE_BAC5',
    'bac 5': 'LICENCE_BAC5',
    'bac+5': 'LICENCE_BAC5',
    'bac +5': 'LICENCE_BAC5',
    'licencie': 'LICENCE_BAC5',
    'licenciee': 'LICENCE_BAC5',
    'gradue': 'GRADUAT_BAC3',
    'graduee': 'GRADUAT_BAC3',
    'formation': 'FORMATION_PROFESSIONNELLE',
    'basique': 'PRIMAIRE',
    'l2': 'LICENCE_BAC5',
    'g3 osp': 'GRADUAT_BAC3',
    'g3': 'GRADUAT_BAC3',
    'master': 'MASTER',
    'dea': 'DEA',
    'doctorat': 'DOCTORAT_PHD',
    'phd': 'DOCTORAT_PHD',
    'post doctorat': 'POST_DOCTORAT',
    'post-doctorat': 'POST_DOCTORAT',
    'formation professionnelle': 'FORMATION_PROFESSIONNELLE',
    'certificat specialise': 'CERTIFICAT_SPECIALISE',
}

DEGREE_ALIASES = {
    "certificat d etudes primaires": 'CERTIFICAT_ETUDES_PRIMAIRES',
    'diplome d etat': 'DIPLOME_ETAT',
    'diplome detat': 'DIPLOME_ETAT',
    'graduat': 'GRADUAT',
    'licence': 'LICENCE',
    'master': 'MASTER',
    'dea': 'DEA',
    'doctorat': 'DOCTORAT',
    'bts': 'BTS',
    'ingenieur': 'INGENIEUR',
    'medecin': 'MEDECIN',
    'pharmacien': 'PHARMACIEN',
    'architecte': 'ARCHITECTE',
    'certificat': 'CERTIFICAT_ETUDES_PRIMAIRES',
    'ingenieur en eaux et forets': 'INGENIEUR',
    'gestion financiere': 'GESTION',
}

FIELD_OF_STUDY_ALIASES = {
    'informatique': 'INFORMATIQUE',
    'info': 'INFORMATIQUE',
    'it': 'INFORMATIQUE',
    'genie logiciel': 'GENIE_LOGICIEL',
    'reseaux': 'RESEAUX',
    'reseaux telecom': 'RESEAUX',
    'reseaux & telecom': 'RESEAUX',
    'telecom': 'TELECOMMUNICATIONS',
    'telecommunications': 'TELECOMMUNICATIONS',
    'ia': 'INTELLIGENCE_ARTIFICIELLE',
    'intelligence artificielle': 'INTELLIGENCE_ARTIFICIELLE',
    'cybersecurite': 'CYBERSECURITE',
    'mathematique informatique': 'MATHEMATIQUE_INFORMATIQUE',
    'mathematiques': 'MATHEMATIQUES',
    'statistiques': 'STATISTIQUES',
    'demographie': 'DEMOGRAPHIE',
    'economie': 'ECONOMIE',
    'gestion': 'GESTION',
    'comptabilite': 'COMPTABILITE',
    'droit': 'DROIT',
    'sciences politiques': 'SCIENCES_POLITIQUES',
    'relations internationales': 'RELATIONS_INTERNATIONALES',
    'administration publique': 'ADMINISTRATION_PUBLIQUE',
    'administration': 'ADMINISTRATION',
    'finance': 'FINANCE',
    'banque': 'BANQUE',
    'marketing': 'MARKETING',
    'ressources humaines': 'RESSOURCES_HUMAINES',
    'rh': 'RESSOURCES_HUMAINES',
    'communication': 'COMMUNICATION',
    'journalisme': 'JOURNALISME',
    'medecine': 'MEDECINE',
    'sante publique': 'SANTE_PUBLIQUE',
    'agronomie': 'AGRONOMIE',
    'genie civil': 'GENIE_CIVIL',
    'architecture': 'ARCHITECTURE',
    'electricite': 'ELECTRICITE',
    'mecanique': 'MECANIQUE',
    'chimie': 'CHIMIE',
    'physique': 'PHYSIQUE',
    'biologie': 'BIOLOGIE',
    'geographie': 'GEOGRAPHIE',
    'histoire': 'HISTOIRE',
    'psychologie': 'PSYCHOLOGIE',
    'sociologie': 'SOCIOLOGIE',
    'philosophie': 'PHILOSOPHIE',
    'langues': 'LANGUES',
    'enseignement': 'ENSEIGNEMENT',
    'geosciences': 'GEOSCIENCES',
    'sciences informatiques': 'INFORMATIQUE',
    'eaux et forets': 'GEOSCIENCES',
    'management': 'GESTION',
    'anglais': 'LANGUES',
    'droit international et relations internationales': 'RELATIONS_INTERNATIONALES',
    'orientation scolaire et professionnel': 'ORIENTATION_SCOLAIRE_PEDAGOGIQUE',
    'orientation scolaire et pedagogique': 'ORIENTATION_SCOLAIRE_PEDAGOGIQUE',
    'orientation scolaire': 'ORIENTATION_SCOLAIRE_PEDAGOGIQUE',
}

INSTITUTION_ALIASES = {
    'unikin': 'UNIKIN',
    'universite de kinshasa': 'UNIKIN',
    'upn': 'UPN',
    'universite pedagogique nationale': 'UPN',
    'universite pedagogique': 'UPN',
    'unilu': 'UNILU',
    'universite de lubumbashi': 'UNILU',
    'unikis': 'UNIKIS',
    'universite de kisangani': 'UNIKIS',
    'unigom': 'UNIGOM',
    'universite de goma': 'UNIGOM',
    'upc': 'UPC',
    'ucc': 'UCC',
    'ulk': 'ULK',
    'ista': 'AUTRES',
}
