# Generated by Django 4.2.7 on 2023-12-06 02:27

import core.models.fields.date_field
import core.models.fields.json_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('place_of_training', models.CharField(max_length=255, null=True, verbose_name='lieu de formation')),
                ('trainer', models.CharField(max_length=255, null=True, verbose_name='formateur')),
                ('has_certificate', models.BooleanField(default=False, help_text='A la fin de la formation, un certificat est délivré.', verbose_name='certificat')),
                ('is_completed', models.BooleanField(default=False, help_text='La formation est-elle achevée ?', verbose_name='terminé')),
                ('start_date', core.models.fields.date_field.DateField(null=True, verbose_name='date de début')),
                ('end_date', core.models.fields.date_field.DateField(null=True, verbose_name='date de fin')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
            },
        ),
    ]
