# Generated by Django 4.2.7 on 2024-01-07 20:01

import core.models.fields.date_field
import core.models.fields.json_field
import core.models.fields.model_select_field
import core.models.fields.time_field
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('max_days_per_year', models.IntegerField(verbose_name='Nombre maximal de jours par an')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'type de congé',
                'verbose_name_plural': 'type de congé',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('start_dt', core.models.fields.date_field.DateField(verbose_name='du')),
                ('end_dt', core.models.fields.date_field.DateField(verbose_name='au')),
                ('reason', models.TextField(default=None, null=True, verbose_name='motif')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('employee', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='employé')),
                ('interim', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interim', to='employee.employee', verbose_name='remplaçant')),
                ('type_of_leave', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.typeofleave', verbose_name='type de congé')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'congé',
                'verbose_name_plural': 'congés',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('paid', models.BooleanField(default=True, verbose_name='payé')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('start_dt', core.models.fields.date_field.DateField(verbose_name='du')),
                ('end_dt', core.models.fields.date_field.DateField(verbose_name='au')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'Fériée',
                'verbose_name_plural': 'Fériées',
            },
        ),
        migrations.CreateModel(
            name='EarlyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('destination', models.CharField(default=None, max_length=250, null=True, verbose_name='destination')),
                ('date', core.models.fields.date_field.DateField(default=datetime.datetime.today, verbose_name='date')),
                ('start_time', core.models.fields.time_field.TimeField(verbose_name='de')),
                ('end_time', core.models.fields.time_field.TimeField(verbose_name='à')),
                ('observation', models.TextField(blank=True, default=None, null=True, verbose_name='observation')),
                ('reason', models.TextField(verbose_name='motif')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('employee', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='employé')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'départ anticipé',
                'verbose_name_plural': 'départs anticipé',
            },
        ),
    ]
