# Generated by Django 4.2.7 on 2025-10-15 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eye_position', models.CharField(choices=[('LEFT', 'Œil gauche'), ('RIGHT', 'Œil droit')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CAPTURED', 'Capturé'), ('BLIND', 'Œil aveugle'), ('MISSING', 'Œil manquant'), ('DAMAGED', 'Œil endommagé'), ('FAILED', 'Échec capture')], default='PENDING', max_length=20)),
                ('full_frame', models.ImageField(blank=True, help_text='Image complète capturée', null=True, upload_to='iris/images/full_frames/')),
                ('eye_region', models.ImageField(blank=True, help_text="Région de l'œil extraite", null=True, upload_to='iris/images/eye_regions/')),
                ('normalized_iris', models.ImageField(blank=True, help_text='Iris normalisé (coordonnées polaires)', null=True, upload_to='iris/images/normalized/')),
                ('segmented_iris', models.ImageField(blank=True, help_text='Iris segmenté avec visualisation', null=True, upload_to='iris/images/segmented/')),
                ('iris_center_x', models.IntegerField(blank=True, null=True)),
                ('iris_center_y', models.IntegerField(blank=True, null=True)),
                ('iris_radius', models.IntegerField(blank=True, null=True)),
                ('pupil_center_x', models.IntegerField(blank=True, null=True)),
                ('pupil_center_y', models.IntegerField(blank=True, null=True)),
                ('pupil_radius', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, help_text='Score de qualité global (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('size_score', models.FloatField(blank=True, null=True)),
                ('centering_score', models.FloatField(blank=True, null=True)),
                ('contrast_score', models.FloatField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='True si qualité suffisante pour enrollment')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iris_captures',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='IrisTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_data', models.BinaryField(help_text='Template binaire encodé (code + mask)')),
                ('encoding_method', models.CharField(default='gabor_phase', help_text="Méthode d'encodage utilisée", max_length=50)),
                ('template_size', models.IntegerField(help_text='Taille du template en bytes')),
                ('code_shape_filters', models.IntegerField(default=8)),
                ('code_shape_height', models.IntegerField(default=64)),
                ('code_shape_width', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='iris.iriscapture')),
            ],
            options={
                'db_table': 'iris_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrisQualityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField()),
                ('size_score', models.FloatField()),
                ('centering_score', models.FloatField()),
                ('contrast_score', models.FloatField()),
                ('sharpness_score', models.FloatField(blank=True, null=True)),
                ('occlusion_score', models.FloatField(blank=True, null=True)),
                ('capture_duration', models.FloatField(help_text='Durée de capture en secondes')),
                ('processing_duration', models.FloatField(help_text='Durée de traitement en secondes')),
                ('pupil_detected', models.BooleanField(default=False)),
                ('iris_detected', models.BooleanField(default=False)),
                ('issues', models.JSONField(default=list, help_text='Liste des problèmes détectés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_log', to='iris.iriscapture')),
            ],
            options={
                'db_table': 'iris_quality_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrisCaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_session_id', models.UUIDField(help_text="ID de la session d'enrôlement parente")),
                ('status', models.CharField(choices=[('INITIATED', 'Initiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Complétée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='INITIATED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_id', models.CharField(blank=True, max_length=50, null=True)),
                ('station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iris_capture_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['enrollment_session_id'], name='iris_captur_enrollm_3c9472_idx'), models.Index(fields=['status'], name='iris_captur_status_0be22b_idx'), models.Index(fields=['started_at'], name='iris_captur_started_0b0a21_idx')],
            },
        ),
        migrations.AddField(
            model_name='iriscapture',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='iris.iriscapturesession'),
        ),
        migrations.CreateModel(
            name='IrisMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_match', models.BooleanField(help_text='True si les iris correspondent')),
                ('similarity_score', models.FloatField(help_text='Score de similarité (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('hamming_distance', models.FloatField(help_text='Distance de Hamming normalisée (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rotation_shift', models.IntegerField(help_text='Décalage de rotation optimal (pixels)')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matching_threshold', models.FloatField(help_text='Seuil utilisé pour la décision')),
                ('template_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_template1', to='iris.iristemplate')),
                ('template_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_template2', to='iris.iristemplate')),
            ],
            options={
                'db_table': 'iris_matches',
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['is_match'], name='iris_matche_is_matc_6633e4_idx'), models.Index(fields=['similarity_score'], name='iris_matche_similar_a8d645_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='iriscapture',
            index=models.Index(fields=['session', 'eye_position'], name='iris_captur_session_cea2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='iriscapture',
            index=models.Index(fields=['status'], name='iris_captur_status_98afd0_idx'),
        ),
        migrations.AddIndex(
            model_name='iriscapture',
            index=models.Index(fields=['is_valid'], name='iris_captur_is_vali_7856ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iriscapture',
            unique_together={('session', 'eye_position')},
        ),
    ]
